# What is NumPy?

* NumPy: python's mathematics package for advanced math operations (more advanced than +, -, *, /).

* This includes special functions like cosine, exponents, sqrt, and so on.

* The reason it is so important for data science is that many libraries used in data science rely on NumPy as one of their main building blocks.

* Additionally, we can use NumPy to generate samples from many types of random variables

* NumPy includes data types to define vectors, matrices, and tensors (which helps with image processing!)



# Installation Instructions
##  (Also, this is how to install MOST libraries in Python):

### !pip install 'PACKAGE NAME'

* where you replace 'PACKAGE NAME' with the packages name :-D

In [1]:
# this is how you install NumPy:
!pip install NumPy

In [2]:
# if you need to update pip, uncomment this code and run it:
# !pip install --upgrade pip

# How to use NumPy

## Once you've installed NumPy you can import it as a library:

In [3]:
# This is how you import a library in Python.
# The general structure is import library_name.
# Best practices dictate that import statements usually go at the beginning of your code/program.
# If a library will be used in a program, it will have to be imported in the code BEFORE it is used.
# If you want to create a shorthand notation for a libary you will be working extensively with throughout a program
# you can add the as 'shorthand'.
# This saves some time if you will be calling the library a lot

import numpy as np

# Here, when we need to call numpy in our code, we can use the shorthand of np.

# Numpy Arrays

* NumPy arrays are the main way we will use NumPy. 
* NumPy arrays essentially come in two flavors: vectors and matrices. 
* Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Creating NumPy arrays from a Python list
* We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Random numbers in NumPy
* Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [8]:
np.random.rand(2)

array([0.32313807, 0.05870691])

In [9]:
np.random.rand(5,5)

array([[0.77554389, 0.64062109, 0.81902185, 0.35846018, 0.13553445],
       [0.15519268, 0.71537745, 0.87723305, 0.95146214, 0.889051  ],
       [0.5275953 , 0.71119825, 0.71926543, 0.91616562, 0.99505282],
       [0.35121685, 0.42727218, 0.13680177, 0.00257832, 0.91366166],
       [0.61912164, 0.37438424, 0.71991018, 0.87319395, 0.38734299]])

### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [10]:
np.random.randn(2)

array([-0.6391497 ,  0.82467411])

In [11]:
np.random.randn(5,5)

array([[ 0.56463649, -0.32434537, -0.44252711, -0.30521821, -0.15178462],
       [-1.47546537,  0.44787493, -0.37538944,  1.84107831,  0.93248631],
       [ 0.05364991, -1.03223179, -0.85291563, -1.21207482, -0.47465946],
       [-0.83780065, -0.32785866,  0.05628778, -0.19723766, -0.11534855],
       [ 1.11240996, -0.57546091, -1.04931809,  0.76384913, -0.044467  ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [12]:
np.random.randint(1,100)

8

In [13]:
np.random.randint(1,100,10)

array([22, 73, 16, 71, 75, 20, 51, 74, 20,  1])

# Array Attributes and Methods

In [14]:
rand_arr = np.random.randint(0,50,10)

### max, min

In [15]:
rand_arr

array([30, 13,  0, 47, 23,  6, 22, 45, 32, 26])

In [16]:
rand_arr.max()

47

In [17]:
rand_arr.min()

0

### Shape

In [18]:
rand_arr.shape

(10,)

In [19]:
my_matrix = np.array(my_matrix)

In [20]:
my_matrix.shape

(3, 3)

### Data type

In [21]:
rand_arr.dtype

dtype('int64')

In [22]:
my_matrix.dtype

dtype('int64')

# NumPy indexing and selection

In [23]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Get a value at an index
arr[8]

8

In [25]:
# Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [26]:
# Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [27]:
# Slicing an array
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

## Indexing a 2D array (matrices)
The general format for indexing a 2D array is **arr_2d[row][col]** or **arr_2d[row,col]**. 

In [28]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
# Print the array
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
# Indexing row 2
arr_2d[1]

array([20, 25, 30])

In [30]:
# Getting an individual element value
arr_2d[1][0]

20

In [31]:
# 2D array slicing
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Universal Array Functions

Numpy comes with universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. 

In [32]:
# create another array:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr2+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr2-arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr2*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [36]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.log(arr2)

/var/folders/27/px9hdzpj7vg6cdlnfkj8j2t40000gn/T/ipykernel_70872/2430268246.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr2)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])